#define BORG_SUCCESSION_LEVEL 0
#define ASSISTANT_SUCCESSION_LEVEL 2
#define INDUCTEE_SUCCESSION_LEVEL 3
#define SENIOR_SUCCESSION_LEVEL 5
#define COMMAND_SUCCESSION_LEVEL 10
#define CAPTAIN_SUCCESION_LEVEL COMMAND_SUCCESSION_LEVEL+2