version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
image: Visual Studio 2017
configuration: Release
clone_depth: 1
artifacts:
- path: tools/tgstation-server-3/ServiceInstaller/Release/**/*
  name: TG Station Server Installer
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
  - ps: tools/appveyor/vs-2017-installer-templates.ps1
before_build:
  - nuget restore tools/tgstation-server-3/TGStationServer3-NoInstaller.sln
build:
  project: tools/tgstation-server-3/TGStationServer3-NoInstaller.sln
  parallel: true
  verbosity: minimal
after_build:
  - cmd: tools/appveyor/build-tgs3-installer.cmd
deploy:
  release: tgstation-server-3-v$(appveyor_build_version)
  description: 'The /tg/station server suite'
  provider: GitHub
  auth_token:
    secure: github_oath_token
  artifact: /.*
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
