version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
image: Visual Studio 2017
configuration: Release
clone_depth: 1
install:
  - ps: tools/appveyor/vs-2017-installer-templates.ps1
before_build:
  - nuget restore tools/tgstation-server-3/TGStationServer3-NoInstaller.sln
build:
  project: tools/tgstation-server-3/TGStationServer3-NoInstaller.sln
  verbosity: minimal