version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
image: Visual Studio 2017
configuration: Release
clone_depth: 1
artifacts:
- path: tools/tgstation-server-3/TGServiceInstaller/bin/Release/*
  name: TG Station Server Installer
before_build:
  - nuget restore tools/tgstation-server-3/TGStationServer3-NoInstaller.sln
build:
  project: tools/tgstation-server-3/TGStationServer3.sln
  parallel: true
  verbosity: minimal
deploy:
  release: tgstation-server-3-v$(appveyor_build_version)
  description: 'The /tg/station server suite'
  provider: GitHub
  auth_token:
    secure: github_oath_token
  artifact: /.*
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
