pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
image: Visual Studio 2017
configuration: Release
clone_depth: 1
artifacts:
- path: TGS3.zip
  name: TGS3
before_build:
  - nuget restore tools/tgstation-server-3/TGStationServer3.sln
build:
  project: tools/tgstation-server-3/TGStationServer3.sln
  parallel: true
  verbosity: minimal
after_build:
  - ps: "tools/appveyor/ZipTGS3Release.ps1"
deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: 'The /tg/station server suite'
  provider: GitHub
  auth_token:
    secure: 9Yf+FtoE7nf36V3dyVRANkNZ7og4dp/0uojCS51vrvIeNOTIM8Nq24lylgVBOhSL
  artifact: TGS3
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
